### ISSUE TITLE
Game unplayable?

### ISSUE THREAD

**Issue by NihalNavath** [North-West-Wind/islandr.io#10]
Is this supposed to happen? I get this when I click on connect.

![Screenshot 2023-03-07 150704](https://user-images.githubusercontent.com/66069728/223382674-3defb2c9-bef3-41a2-b2de-d8fb8e4ecb79.png)

**Comment by North-West-Wind** [comment]
Press F12 and see if there are any errors in the console?

**Comment by North-West-Wind** [comment]
Also, maybe you are running an old version from yesterday. One of the commits yesterday caused this, and I fixed it.

**Comment by NihalNavath** [comment]
> Also, maybe you are running an old version from yesterday. One of the commits yesterday caused this, and I fixed it.

Git pull shows I am up to date? 

When I open console there are plently of errors that starts with 
"Cannot read properties of undefined (reading 'name')"

**Comment by Viswas-Programs** [comment]
I mean, did you sync your fork with the main repo?
If you didn't know already (which I higly doubt) go to your fork, and click on Sync fork button below the "code" button.

**Comment by Viswas-Programs** [comment]
> Git pull shows I am up to date?
> 
> When I open console there are plently of errors that starts with "Cannot read properties of undefined (reading 'name')"


 Read my above comment, and if it's still there, try rebuilding your server and client files, and if that doesn't work, try downloading the server and client files, put it in a different folder and try compiling and building that. 
Then, if that downloaded copy works, then your copy must be corrupted, and try to get the differences between the files, maybe some thing would've happened while pulling, with the merge conflicts doing something wrong?

**Comment by North-West-Wind** [comment]
> > Also, maybe you are running an old version from yesterday. One of the commits yesterday caused this, and I fixed it.
> 
> Git pull shows I am up to date?
> 
> When I open console there are plently of errors that starts with "Cannot read properties of undefined (reading 'name')"

Anything following that?

**Comment by NihalNavath** [comment]
> > > Also, maybe you are running an old version from yesterday. One of the commits yesterday caused this, and I fixed it.
> > 
> > 
> > Git pull shows I am up to date?
> > When I open console there are plently of errors that starts with "Cannot read properties of undefined (reading 'name')"
> 
> Anything following that?

just bunch of errors 

![image](https://user-images.githubusercontent.com/66069728/223622407-53be2920-2cf0-4fbc-8d6c-f92630d59665.png)

**Comment by Viswas-Programs** [comment]
One question: did you name youself with some random name with a lot of symbols? maybe that could cause a problem? 
Like a semicolon in the name?

**Comment by North-West-Wind** [comment]
That `name` should not be related to username. I pushed quite a few commits since then. Try updating and see if it got fixed?

**Comment by NihalNavath** [comment]
Opps forgot I was running a fork. That fixed it.
