### ISSUE TITLE
The trees dissapeared?

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/islandr.io#3]
The trees are not showing up, the bushes are tiny bro!
Anyway, I am trying to make the crate spawn, 20% done bro. 
Thank you bro for all of this improvements.
One other thing is that the residues don't show up.

**Comment by North-West-Wind** [comment]
I'm doing a lot of unstable pushes recently. Those bugs are the remnant of my trial and error.

Also the trees properly didn't disappear. They just like to aggregate at a corner of the map. The latest push should have fixed it.

As for the tiny bushes, those should be fixed in the next few pushes.
