### ISSUE TITLE
The gun drop doesn't work properly

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/islandr.io#5]
The gun spawns from the crate, but only the outer frame displays, like the ammo type, not the gun shape (or gun image) itself, here's the image of what I am saying. 
Btw, I am going to create a mosin tree, and a ak47 rock, so i take up that responsibility.
And, I came back to this project developement 
after a long time (1-2 months)
IMAGE:
![Screenshot from 2023-01-18 19-54-10](https://user-images.githubusercontent.com/115633223/213196527-7a051e55-21de-4cb5-a71e-e7d2fd3aaccc.png)

**Comment by North-West-Wind** [comment]
It is still not complete. I also took a break.

**Comment by Viswas-Programs** [comment]
Oh yeah sure. 
I also am taking a break from this program.

**Comment by ZEROPOINTBRUH** [comment]
bump

**Comment by Viswas-Programs** [comment]
@ZEROPOINTBRUH what?

**Comment by ZEROPOINTBRUH** [comment]
Bumping the issue (its a term for reinstating the issue is valid or pushing the discussion)

**Comment by Viswas-Programs** [comment]
oh ok, and welcome to this project!

**Comment by Viswas-Programs** [comment]
> Bumping the issue (its a term for reinstating the issue is valid or pushing the discussion)

Thank you for bumping the issue, now the Maintained has fixed the issue, by adding names into the gun frame.
