### ISSUE TITLE
The weapon switcher is showing all fists!

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/islandr.io#8]
https://clipchamp.com/watch/wnXGkHLTHbz This is the video explaining all the issues with opensurviv.io.
![image](https://user-images.githubusercontent.com/115633223/223080108-8e097fb3-1b73-4b15-9e33-c7048e55c8ab.png)
![image](https://user-images.githubusercontent.com/115633223/223080323-a07a699f-6ed9-4e18-a7d0-332316b862ee.png)

All of them are showing as FIsts, and when I reach the limit, sometimes, the server crashes outright!

**Comment by Viswas-Programs** [comment]
Adding on to that, whenever I pick up Mosin Nagant, it's showing fine, and actually showing mosin nagant in the switcher, but, when I switch to mosin, the speed is boosted, but if I change back to Fists, the speed drops below
Btw, the speed, when having the mosin, is the correct speed, for all of the days this existed, the speed was really low!

**Comment by Viswas-Programs** [comment]
Yeah bro, now it works, and the weird speed up thing with mosin nagant is not happening anymore. 
But, before this patch, why, Mosin Nagant worked, while others didn't? 😕

**Comment by North-West-Wind** [comment]
It's because I used weapon names instead of IDs. The server tries to find the weapon with that ID, but fails because name != ID. Fists is the fallback weapon when it fails.

**Comment by Viswas-Programs** [comment]
Oh but mosin has the ID and name same, so it worked? thanks for clarification bro.
