### ISSUE TITLE
The new update issues

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/islandr.io#9]
The issues are the fists not being spam clickable, there is a second delay before you can hit another time with the fists.
But, before this update (latest one), it was not having this issue, this was spam clickable, but not now.
This is big issue, because in real life use, using pistols and fist fighting is a part of the now not existing surviv.io. So, we shouldn't remove it.

**Comment by North-West-Wind** [comment]
Yeah that was not great was it

**Comment by Viswas-Programs** [comment]
yeah that ain't great, and also, I have a suggestion that I can't add (because Idk how to), but if you can (highly yes), then one of my suggestions would be to add a player alive count. I achieved like 70% of it, but didn't know how to add it to the web page, but the type script code I finished that. 
So if you know, please make that

**Comment by North-West-Wind** [comment]
70%? Make a PR for that. I can probably take care of the rest of it.

**Comment by Viswas-Programs** [comment]
Ok 70% was an exaggeration, but, the typescript code, I completed that (it was simple enough to do that!) I only struggled how to get uptodate alive count in the HTML webpage, like an Ingame overlay, that was my problem
